### ISSUE TITLE
Monorepo

### ISSUE THREAD

**Issue by modulovalue** [TerminalStudio/studio#5]
Hello @xtyxtyx

Could you make this project a monorepo? 
That is, have studio or xterm contain all the packages and not include them via git submodules.

This makes it difficult to contribute changes that possibly involve all packages as they would require 5 separate pull requests.

cc @devmil

**Comment by xtyxtyx** [comment]
Thank you for your suggestion!

Since `context_menu_macos` and `tabs` is depended only by `studio`, I think it totally makes sense to move them inside `studio` and will do that shortly.

As to `pty` and `xterm`, which are published to pub.dev and depended by projects other than `studio`, I feel it better to keep them standalone so they can be developed and tagged individually.

**Comment by modulovalue** [comment]
> I think it totally makes sense to move them inside studio and will do that shortly.

(just so that there's no misunderstanding, I am not suggesting you to merge all packages into one, just to have one repo with all of the packages inside of that single repo)

Thank you for the answer. I'll have to think about it.

**Comment by devmil** [comment]
One idea from my sie: I'm using git subrepo to get and sync the repositories into my terminal.
Might be something worth considering
https://github.com/ingydotnet/git-subrepo
